### ISSUE TITLE
Phone calls do not go through the LivePhone app (iOS, Android)

### ISSUE THREAD

**Issue by Kubo94** [QualityUnit/LivePhone-iOS#3]
I am available to receive calls with the number in use in a specific department in LivePhone app BUT the calls always ring within the LiveAgent dashboard instead of LivePhone app
See my settings (screenshots) but I tried all variations

![98484483_176317997048599_995343178900963328_n](https://user-images.githubusercontent.com/47157155/82339697-9cca6f00-99ee-11ea-9a6b-21b42d10bca6.jpg)
![Call_from_18882578754_Safe_Health_Support (3)](https://user-images.githubusercontent.com/47157155/82339712-a18f2300-99ee-11ea-87c8-aa6c51e6cd68.png)
![Call_from_18882578754_Safe_Health_Support (2)](https://user-images.githubusercontent.com/47157155/82339728-a6ec6d80-99ee-11ea-85ca-c008fbe9269b.png)
![Call_from_18882578754_Safe_Health_Support (1)](https://user-images.githubusercontent.com/47157155/82339744-abb12180-99ee-11ea-9250-7cb08232ae33.png)

safehealth.ladesk.com
5.17.25.1

iOS 13.4.1

**Comment by Kubo94** [comment]
HFJ-RVRRN-261

**Comment by rkostrab** [comment]
I was testing this. While testing there was 9 agents online for calls in the called department.
![Snímka obrazovky 2020-05-19 o 16 41 11](https://user-images.githubusercontent.com/8927467/82341172-5d048700-99f0-11ea-953a-7d36044b6abb.png)

First and second test call was redirected to Marcus Bennett, because of an error "Device not found" both calls dropped into voicemail.

Third test call after the same error came to LivePhone app successfully.
![Snímka obrazovky 2020-05-19 o 16 52 29](https://user-images.githubusercontent.com/8927467/82342381-d6e94000-99f1-11ea-9f58-fdc4ac64ece6.png)
